package uk.co.rodrunners.raffles.core

object Collections {
    const val USERS = "users"
    const val USER_SIGNUPS = "userSignups"
    const val COMPETITIONS = "competitions"
    const val ENTRIES = "entries"
    const val ORDERS = "orders"
    const val WINNERS = "winners"
    const val FAVOURITES = "favourites"
    const val NOTIFICATIONS = "notifications"
    const val SUPPORT_TICKETS = "supportTickets"
    const val FAQ = "faq"
    const val APP_CONTENT = "appContent"
    const val ADMIN_USERS = "adminUsers"
    const val PROMOTIONS = "promotions"
    const val AUDIT_LOGS = "auditLogs"
    const val INSTANT_WINS = "instantWins"
    const val CREDIT_LEDGER = "creditLedger"
    const val DAILY_SPINS = "dailySpins"
    const val GAME_SCORES = "gameScores"
}

object Functions {
    const val REGION = "europe-west2"
    const val QUOTE_BASKET = "quoteBasket"
    const val CREATE_ORDER = "createOrderAndPaymentIntent"
    const val APPLY_PROMO = "applyPromoCode"
    const val REGISTER_TOKEN = "registerFcmToken"
    const val DELETE_ACCOUNT = "deleteMyAccount"
    const val CREATE_TICKET = "createSupportTicket"
    const val REPLY_TICKET = "replyToTicket"
    const val CLOSE_COMPETITION = "closeCompetition"
    const val DRAW_WINNER = "drawWinner"
    const val PUBLISH_RESULT = "publishResult"
    const val SET_COMPETITION_STATUS = "setCompetitionStatus"
    const val REFUND_ORDER = "refundOrder"
    const val SUSPEND_CUSTOMER = "suspendCustomer"
    const val SEED_DEMO = "seedDemoData"
    const val CREATE_COMPETITION = "createCompetition"
    const val UPDATE_COMPETITION = "updateCompetition"
    const val DELETE_DRAFT_COMPETITION = "deleteDraftCompetition"
    const val ADD_INSTANT_WINS = "addInstantWinPrizes"
    const val LIST_INSTANT_WINS = "listInstantWins"
    const val REMOVE_INSTANT_WINS = "removeInstantWinPrizes"
    const val SET_INSTANT_WIN_CLAIM = "setInstantWinClaimStatus"
    const val BOOTSTRAP_FIRST_ADMIN = "bootstrapFirstAdmin"
    const val LIST_ADMIN_USERS = "listAdminUsers"
    const val GRANT_ADMIN = "grantAdminByEmail"
    const val REVOKE_ADMIN = "revokeAdmin"
    const val REDEEM_COUPON = "redeemCreditCoupon"
    const val CREATE_COUPON = "createCreditCoupon"
    const val LIST_COUPONS = "listCreditCoupons"
    const val SET_COUPON_ACTIVE = "setCreditCouponActive"
    const val SPIN_DAILY_WHEEL = "spinDailyWheel"
    const val GRANT_CREDIT = "grantCredit"
    const val SUBMIT_GAME_CATCH = "submitGameCatch"
    const val GAME_LEADERBOARD = "gameLeaderboard"
}

object NotificationChannels {
    const val GENERAL = "rrr_general"
    const val ORDERS = "rrr_orders"
    const val RAFFLES = "rrr_raffles"
    const val WINS = "rrr_wins"
    const val PROMOTIONS = "rrr_promotions"
}

object Topics {
    const val NEW_COMPETITIONS = "new_competitions"
    const val RESULTS = "results"
}
